// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SEBT.Portal.StatePlugins.CO.CbmsApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Address : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The addrLn1 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddrLn1 { get; set; }
#nullable restore
#else
        public string AddrLn1 { get; set; }
#endif
        /// <summary>The addrLn2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddrLn2 { get; set; }
#nullable restore
#else
        public string AddrLn2 { get; set; }
#endif
        /// <summary>The cty property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cty { get; set; }
#nullable restore
#else
        public string Cty { get; set; }
#endif
        /// <summary>The staCd property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StaCd { get; set; }
#nullable restore
#else
        public string StaCd { get; set; }
#endif
        /// <summary>The zip property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Zip { get; set; }
#nullable restore
#else
        public string Zip { get; set; }
#endif
        /// <summary>The zip4 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Zip4 { get; set; }
#nullable restore
#else
        public string Zip4 { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::SEBT.Portal.StatePlugins.CO.CbmsApi.Models.Address"/> and sets the default values.
        /// </summary>
        public Address()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SEBT.Portal.StatePlugins.CO.CbmsApi.Models.Address"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SEBT.Portal.StatePlugins.CO.CbmsApi.Models.Address CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SEBT.Portal.StatePlugins.CO.CbmsApi.Models.Address();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "addrLn1", n => { AddrLn1 = n.GetStringValue(); } },
                { "addrLn2", n => { AddrLn2 = n.GetStringValue(); } },
                { "cty", n => { Cty = n.GetStringValue(); } },
                { "staCd", n => { StaCd = n.GetStringValue(); } },
                { "zip", n => { Zip = n.GetStringValue(); } },
                { "zip4", n => { Zip4 = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("addrLn1", AddrLn1);
            writer.WriteStringValue("addrLn2", AddrLn2);
            writer.WriteStringValue("cty", Cty);
            writer.WriteStringValue("staCd", StaCd);
            writer.WriteStringValue("zip", Zip);
            writer.WriteStringValue("zip4", Zip4);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
