// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SEBT.Portal.StatePlugins.CO.CbmsApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CheckEnrollmentRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cbmsCsId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CbmsCsId { get; set; }
#nullable restore
#else
        public string CbmsCsId { get; set; }
#endif
        /// <summary>The sebtYear property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SebtYear { get; set; }
#nullable restore
#else
        public string SebtYear { get; set; }
#endif
        /// <summary>The stdDob property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StdDob { get; set; }
#nullable restore
#else
        public string StdDob { get; set; }
#endif
        /// <summary>The stdFirstName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StdFirstName { get; set; }
#nullable restore
#else
        public string StdFirstName { get; set; }
#endif
        /// <summary>The stdLastName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StdLastName { get; set; }
#nullable restore
#else
        public string StdLastName { get; set; }
#endif
        /// <summary>The stdReqInd property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StdReqInd { get; set; }
#nullable restore
#else
        public string StdReqInd { get; set; }
#endif
        /// <summary>The stdSasId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StdSasId { get; set; }
#nullable restore
#else
        public string StdSasId { get; set; }
#endif
        /// <summary>The stdSchlCd property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StdSchlCd { get; set; }
#nullable restore
#else
        public string StdSchlCd { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::SEBT.Portal.StatePlugins.CO.CbmsApi.Models.CheckEnrollmentRequest"/> and sets the default values.
        /// </summary>
        public CheckEnrollmentRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SEBT.Portal.StatePlugins.CO.CbmsApi.Models.CheckEnrollmentRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SEBT.Portal.StatePlugins.CO.CbmsApi.Models.CheckEnrollmentRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SEBT.Portal.StatePlugins.CO.CbmsApi.Models.CheckEnrollmentRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cbmsCsId", n => { CbmsCsId = n.GetStringValue(); } },
                { "sebtYear", n => { SebtYear = n.GetStringValue(); } },
                { "stdDob", n => { StdDob = n.GetStringValue(); } },
                { "stdFirstName", n => { StdFirstName = n.GetStringValue(); } },
                { "stdLastName", n => { StdLastName = n.GetStringValue(); } },
                { "stdReqInd", n => { StdReqInd = n.GetStringValue(); } },
                { "stdSasId", n => { StdSasId = n.GetStringValue(); } },
                { "stdSchlCd", n => { StdSchlCd = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cbmsCsId", CbmsCsId);
            writer.WriteStringValue("sebtYear", SebtYear);
            writer.WriteStringValue("stdDob", StdDob);
            writer.WriteStringValue("stdFirstName", StdFirstName);
            writer.WriteStringValue("stdLastName", StdLastName);
            writer.WriteStringValue("stdReqInd", StdReqInd);
            writer.WriteStringValue("stdSasId", StdSasId);
            writer.WriteStringValue("stdSchlCd", StdSchlCd);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
