// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SEBT.Portal.StatePlugins.CO.CbmsApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CheckEnrollmentStudentDetail : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The mtchCnfd property</summary>
        public double? MtchCnfd { get; set; }
        /// <summary>The sebtAppId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SebtAppId { get; set; }
#nullable restore
#else
        public string SebtAppId { get; set; }
#endif
        /// <summary>The sebtChldId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SebtChldId { get; set; }
#nullable restore
#else
        public string SebtChldId { get; set; }
#endif
        /// <summary>The sebtYear property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SebtYear { get; set; }
#nullable restore
#else
        public string SebtYear { get; set; }
#endif
        /// <summary>The stdDob property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StdDob { get; set; }
#nullable restore
#else
        public string StdDob { get; set; }
#endif
        /// <summary>The stdFstNm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StdFstNm { get; set; }
#nullable restore
#else
        public string StdFstNm { get; set; }
#endif
        /// <summary>The stdLstNm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StdLstNm { get; set; }
#nullable restore
#else
        public string StdLstNm { get; set; }
#endif
        /// <summary>The stdntEligSts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StdntEligSts { get; set; }
#nullable restore
#else
        public string StdntEligSts { get; set; }
#endif
        /// <summary>The stdReqInd property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StdReqInd { get; set; }
#nullable restore
#else
        public string StdReqInd { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::SEBT.Portal.StatePlugins.CO.CbmsApi.Models.CheckEnrollmentStudentDetail"/> and sets the default values.
        /// </summary>
        public CheckEnrollmentStudentDetail()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SEBT.Portal.StatePlugins.CO.CbmsApi.Models.CheckEnrollmentStudentDetail"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SEBT.Portal.StatePlugins.CO.CbmsApi.Models.CheckEnrollmentStudentDetail CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SEBT.Portal.StatePlugins.CO.CbmsApi.Models.CheckEnrollmentStudentDetail();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "mtchCnfd", n => { MtchCnfd = n.GetDoubleValue(); } },
                { "sebtAppId", n => { SebtAppId = n.GetStringValue(); } },
                { "sebtChldId", n => { SebtChldId = n.GetStringValue(); } },
                { "sebtYear", n => { SebtYear = n.GetStringValue(); } },
                { "stdDob", n => { StdDob = n.GetStringValue(); } },
                { "stdFstNm", n => { StdFstNm = n.GetStringValue(); } },
                { "stdLstNm", n => { StdLstNm = n.GetStringValue(); } },
                { "stdReqInd", n => { StdReqInd = n.GetStringValue(); } },
                { "stdntEligSts", n => { StdntEligSts = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("mtchCnfd", MtchCnfd);
            writer.WriteStringValue("sebtAppId", SebtAppId);
            writer.WriteStringValue("sebtChldId", SebtChldId);
            writer.WriteStringValue("sebtYear", SebtYear);
            writer.WriteStringValue("stdDob", StdDob);
            writer.WriteStringValue("stdFstNm", StdFstNm);
            writer.WriteStringValue("stdLstNm", StdLstNm);
            writer.WriteStringValue("stdntEligSts", StdntEligSts);
            writer.WriteStringValue("stdReqInd", StdReqInd);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
