// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SEBT.Portal.StatePlugins.CO.CbmsApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetAccountStudentDetail : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The addrLn1 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddrLn1 { get; set; }
#nullable restore
#else
        public string AddrLn1 { get; set; }
#endif
        /// <summary>The addrLn2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddrLn2 { get; set; }
#nullable restore
#else
        public string AddrLn2 { get; set; }
#endif
        /// <summary>The benAvalDt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BenAvalDt { get; set; }
#nullable restore
#else
        public string BenAvalDt { get; set; }
#endif
        /// <summary>The benExpDt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BenExpDt { get; set; }
#nullable restore
#else
        public string BenExpDt { get; set; }
#endif
        /// <summary>The cardBal property</summary>
        public double? CardBal { get; set; }
        /// <summary>The cardIssDt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CardIssDt { get; set; }
#nullable restore
#else
        public string CardIssDt { get; set; }
#endif
        /// <summary>The cbmsCsId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CbmsCsId { get; set; }
#nullable restore
#else
        public string CbmsCsId { get; set; }
#endif
        /// <summary>The cty property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cty { get; set; }
#nullable restore
#else
        public string Cty { get; set; }
#endif
        /// <summary>The dircEligSrc property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DircEligSrc { get; set; }
#nullable restore
#else
        public string DircEligSrc { get; set; }
#endif
        /// <summary>The ebtCardLastFour property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EbtCardLastFour { get; set; }
#nullable restore
#else
        public string EbtCardLastFour { get; set; }
#endif
        /// <summary>The ebtCardSts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EbtCardSts { get; set; }
#nullable restore
#else
        public string EbtCardSts { get; set; }
#endif
        /// <summary>The eligSrc property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EligSrc { get; set; }
#nullable restore
#else
        public string EligSrc { get; set; }
#endif
        /// <summary>The gurdEmailAddr property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GurdEmailAddr { get; set; }
#nullable restore
#else
        public string GurdEmailAddr { get; set; }
#endif
        /// <summary>The gurdFstNm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GurdFstNm { get; set; }
#nullable restore
#else
        public string GurdFstNm { get; set; }
#endif
        /// <summary>The gurdLstNm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GurdLstNm { get; set; }
#nullable restore
#else
        public string GurdLstNm { get; set; }
#endif
        /// <summary>The gurdPhnNm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GurdPhnNm { get; set; }
#nullable restore
#else
        public string GurdPhnNm { get; set; }
#endif
        /// <summary>The mtchCnfd property</summary>
        public double? MtchCnfd { get; set; }
        /// <summary>The sebtAppId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SebtAppId { get; set; }
#nullable restore
#else
        public string SebtAppId { get; set; }
#endif
        /// <summary>The sebtAppSts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SebtAppSts { get; set; }
#nullable restore
#else
        public string SebtAppSts { get; set; }
#endif
        /// <summary>The sebtChldCwin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SebtChldCwin { get; set; }
#nullable restore
#else
        public string SebtChldCwin { get; set; }
#endif
        /// <summary>The sebtChldId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SebtChldId { get; set; }
#nullable restore
#else
        public string SebtChldId { get; set; }
#endif
        /// <summary>The sebtYear property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SebtYear { get; set; }
#nullable restore
#else
        public string SebtYear { get; set; }
#endif
        /// <summary>The staCd property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StaCd { get; set; }
#nullable restore
#else
        public string StaCd { get; set; }
#endif
        /// <summary>The stdDob property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StdDob { get; set; }
#nullable restore
#else
        public string StdDob { get; set; }
#endif
        /// <summary>The stdFstNm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StdFstNm { get; set; }
#nullable restore
#else
        public string StdFstNm { get; set; }
#endif
        /// <summary>The stdLstNm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StdLstNm { get; set; }
#nullable restore
#else
        public string StdLstNm { get; set; }
#endif
        /// <summary>The stdntEligSts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StdntEligSts { get; set; }
#nullable restore
#else
        public string StdntEligSts { get; set; }
#endif
        /// <summary>The zip property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Zip { get; set; }
#nullable restore
#else
        public string Zip { get; set; }
#endif
        /// <summary>The zip4 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Zip4 { get; set; }
#nullable restore
#else
        public string Zip4 { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::SEBT.Portal.StatePlugins.CO.CbmsApi.Models.GetAccountStudentDetail"/> and sets the default values.
        /// </summary>
        public GetAccountStudentDetail()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SEBT.Portal.StatePlugins.CO.CbmsApi.Models.GetAccountStudentDetail"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SEBT.Portal.StatePlugins.CO.CbmsApi.Models.GetAccountStudentDetail CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SEBT.Portal.StatePlugins.CO.CbmsApi.Models.GetAccountStudentDetail();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "addrLn1", n => { AddrLn1 = n.GetStringValue(); } },
                { "addrLn2", n => { AddrLn2 = n.GetStringValue(); } },
                { "benAvalDt", n => { BenAvalDt = n.GetStringValue(); } },
                { "benExpDt", n => { BenExpDt = n.GetStringValue(); } },
                { "cardBal", n => { CardBal = n.GetDoubleValue(); } },
                { "cardIssDt", n => { CardIssDt = n.GetStringValue(); } },
                { "cbmsCsId", n => { CbmsCsId = n.GetStringValue(); } },
                { "cty", n => { Cty = n.GetStringValue(); } },
                { "dircEligSrc", n => { DircEligSrc = n.GetStringValue(); } },
                { "ebtCardLastFour", n => { EbtCardLastFour = n.GetStringValue(); } },
                { "ebtCardSts", n => { EbtCardSts = n.GetStringValue(); } },
                { "eligSrc", n => { EligSrc = n.GetStringValue(); } },
                { "gurdEmailAddr", n => { GurdEmailAddr = n.GetStringValue(); } },
                { "gurdFstNm", n => { GurdFstNm = n.GetStringValue(); } },
                { "gurdLstNm", n => { GurdLstNm = n.GetStringValue(); } },
                { "gurdPhnNm", n => { GurdPhnNm = n.GetStringValue(); } },
                { "mtchCnfd", n => { MtchCnfd = n.GetDoubleValue(); } },
                { "sebtAppId", n => { SebtAppId = n.GetStringValue(); } },
                { "sebtAppSts", n => { SebtAppSts = n.GetStringValue(); } },
                { "sebtChldCwin", n => { SebtChldCwin = n.GetStringValue(); } },
                { "sebtChldId", n => { SebtChldId = n.GetStringValue(); } },
                { "sebtYear", n => { SebtYear = n.GetStringValue(); } },
                { "staCd", n => { StaCd = n.GetStringValue(); } },
                { "stdDob", n => { StdDob = n.GetStringValue(); } },
                { "stdFstNm", n => { StdFstNm = n.GetStringValue(); } },
                { "stdLstNm", n => { StdLstNm = n.GetStringValue(); } },
                { "stdntEligSts", n => { StdntEligSts = n.GetStringValue(); } },
                { "zip", n => { Zip = n.GetStringValue(); } },
                { "zip4", n => { Zip4 = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("addrLn1", AddrLn1);
            writer.WriteStringValue("addrLn2", AddrLn2);
            writer.WriteStringValue("benAvalDt", BenAvalDt);
            writer.WriteStringValue("benExpDt", BenExpDt);
            writer.WriteDoubleValue("cardBal", CardBal);
            writer.WriteStringValue("cardIssDt", CardIssDt);
            writer.WriteStringValue("cbmsCsId", CbmsCsId);
            writer.WriteStringValue("cty", Cty);
            writer.WriteStringValue("dircEligSrc", DircEligSrc);
            writer.WriteStringValue("ebtCardLastFour", EbtCardLastFour);
            writer.WriteStringValue("ebtCardSts", EbtCardSts);
            writer.WriteStringValue("eligSrc", EligSrc);
            writer.WriteStringValue("gurdEmailAddr", GurdEmailAddr);
            writer.WriteStringValue("gurdFstNm", GurdFstNm);
            writer.WriteStringValue("gurdLstNm", GurdLstNm);
            writer.WriteStringValue("gurdPhnNm", GurdPhnNm);
            writer.WriteDoubleValue("mtchCnfd", MtchCnfd);
            writer.WriteStringValue("sebtAppId", SebtAppId);
            writer.WriteStringValue("sebtAppSts", SebtAppSts);
            writer.WriteStringValue("sebtChldCwin", SebtChldCwin);
            writer.WriteStringValue("sebtChldId", SebtChldId);
            writer.WriteStringValue("sebtYear", SebtYear);
            writer.WriteStringValue("staCd", StaCd);
            writer.WriteStringValue("stdDob", StdDob);
            writer.WriteStringValue("stdFstNm", StdFstNm);
            writer.WriteStringValue("stdLstNm", StdLstNm);
            writer.WriteStringValue("stdntEligSts", StdntEligSts);
            writer.WriteStringValue("zip", Zip);
            writer.WriteStringValue("zip4", Zip4);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
