// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using SEBT.Portal.StatePlugins.CO.CbmsApi.Sebt.CheckEnrollment;
using SEBT.Portal.StatePlugins.CO.CbmsApi.Sebt.GetAccountDetails;
using SEBT.Portal.StatePlugins.CO.CbmsApi.Sebt.UpdateStdDtls;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SEBT.Portal.StatePlugins.CO.CbmsApi.Sebt
{
    /// <summary>
    /// Builds and executes requests for operations under \sebt
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SebtRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The checkEnrollment property</summary>
        public global::SEBT.Portal.StatePlugins.CO.CbmsApi.Sebt.CheckEnrollment.CheckEnrollmentRequestBuilder CheckEnrollment
        {
            get => new global::SEBT.Portal.StatePlugins.CO.CbmsApi.Sebt.CheckEnrollment.CheckEnrollmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getAccountDetails property</summary>
        public global::SEBT.Portal.StatePlugins.CO.CbmsApi.Sebt.GetAccountDetails.GetAccountDetailsRequestBuilder GetAccountDetails
        {
            get => new global::SEBT.Portal.StatePlugins.CO.CbmsApi.Sebt.GetAccountDetails.GetAccountDetailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The updateStdDtls property</summary>
        public global::SEBT.Portal.StatePlugins.CO.CbmsApi.Sebt.UpdateStdDtls.UpdateStdDtlsRequestBuilder UpdateStdDtls
        {
            get => new global::SEBT.Portal.StatePlugins.CO.CbmsApi.Sebt.UpdateStdDtls.UpdateStdDtlsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SEBT.Portal.StatePlugins.CO.CbmsApi.Sebt.SebtRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SebtRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sebt", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SEBT.Portal.StatePlugins.CO.CbmsApi.Sebt.SebtRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SebtRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sebt", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
